version: "3"

services:
  projetLC-app:
    image: projetLC-app:latest
    env_file:
      - .env
    build: ./app
      dockerfile: vuejs.Dockerfile
    ports:
      - 8080:8080


  projetLC-api:
    image: projetLC-api:latest
    env_file:
      - .env
    build: ./api
      dockerfile: nodejs.Dockerfile
    ports:
      - 8081:9000
    links:
      - projetLC-app
